### PR TITLE
Add random future date generator

### PR DESCRIPTION
**Pull request by harin49**

### CODE REVIEW

**Review by akulsr0 — COMMENTED** [review]
You have nicely done it. Can you add the doc for the same in README.md

**Comment by harin49** [comment]
> You have nicely done it. Can you add the doc for the same in README.md

sure! I also wanted to talk to you about using TSlint, prettier and husky to maintain the integrity of the code base during contribution. let me know if you are up for a convo!

**Comment by akulsr0** [comment]
> > You have nicely done it. Can you add the doc for the same in README.md
> 
> sure! I also wanted to talk to you about using TSlint, prettier and husky to maintain the integrity of the code base during contribution. let me know if you are up for a convo!

Thanks, add it in the docs, and will add prettier config.

**Comment by harin49** [comment]
done!

**Review by akulsr0 — APPROVED** [review]

**Pull request merged**
